// Auth Slice
export {
  default as authReducer,
  login,
  logout,
  updateTokens,
  updateUser,
  selectAuth,
  selectUser,
  selectToken,
  selectAccessToken,
  selectRefreshToken,
  selectIsAuthenticated,
} from './authSlice';

// UI Slice
export {
  default as uiReducer,
  setNavigation,
  setStudentSidebarOpen,
  setAdminSidebarOpen,
  setGlobalLoading,
  addNotification,
  removeNotification,
  clearNotifications,
  openLoginPopup,
  closeLoginPopup,
  toggleLoginPopup,
  selectUI,
  selectCurrentNavigation,
  selectStudentSidebarOpen,
  selectAdminSidebarOpen,
  selectGlobalLoading,
  selectNotifications,
} from './uiSlice';

// Student Slice
export {
  default as studentReducer,
  // Thunks
  fetchDashboard,
  fetchProfile,
  fetchMyCourses,
  fetchCourseDetails,
  fetchCourseModules,
  fetchQuizzesByCourse,
  fetchCourseQuizzes,
  fetchAssignmentsByCourse,
  fetchCourseAssignments,
  fetchCertificates,
  fetchLeaderboard,
  fetchReferralInfo,
  fetchSupportQueries,
  // Actions
  clearStudentData,
  updateProfileLocal,
  invalidateDashboard,
  invalidateProfile,
  invalidateCourses,
  invalidateCertificates,
  // Selectors
  selectDashboard,
  selectDashboardData,
  selectDashboardLoading,
  selectProfile,
  selectProfileData,
  selectProfileLoading,
  selectCourses,
  selectCoursesList,
  selectCoursesLoading,
  selectCourseDetails,
  selectCourseModules,
  selectQuizzes,
  selectQuizzesByCourse,
  selectCourseQuizzes,
  selectAssignments,
  selectAssignmentsByCourse,
  selectCourseAssignments,
  selectCertificates,
  selectCertificatesList,
  selectLeaderboard,
  selectReferral,
  selectReferralData,
  selectSupport,
  selectSupportQueries,
} from './studentSlice';

